[package]
name = "kernel"
description = "Structural law kernel embedded by ectropy."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[dependencies]
grammar = { path = "../grammar" }
plumb = { version = "=0.16.0", registry = "perish" }
serde = { version = "1.0", features = ["derive"] }
toml = "0.9"
